### ISSUE TITLE
Download item page can be accessed directly

### ISSUE THREAD

**Issue by erommel** [Arsenal21/simple-download-monitor#25]
Example: https://desertfox.me/miniserv/cleanwp/sdm_downloads/test-download/

Not sure is this intended or not. @Arsenal21 , should this be addressed or leave it like that? E.g. should direct access to Downloads posts from the frontend be disabled or not?

**Comment by appthemes7** [comment]
This is intentional. You can just share the download page that is created by this plugin and your visitors can download the item or you can embed the download button on another WP page

**Comment by Arsenal21** [comment]
This is intentional. You can just share the download page that is created by this plugin and your visitors can download the item or you can embed the download button on another WP page
