### ISSUE TITLE
Version 3.7.7

### ISSUE THREAD

**Issue by certilremy** [Arsenal21/simple-download-monitor#44]
After update I can't access my website. when I deactivate it everything works. but all data on my website is for download. That's mean my website is useless . I tried to roll on your previous version with the rollback plugin for WordPress found the following error: 

It appears there are no version to select. This is likely due to the plugin author not using tags for their versions and only committing new releases to the repository trunk.

**Comment by Arsenal21** [comment]
Which version did you update it from you? It is likely your server is using a very old version of PHP that is no longer supported by WordPress. What is the PHP version on your server?

**Comment by erommel** [comment]
You can get previous plugin versions from this page https://wordpress.org/plugins/simple-download-monitor/advanced/

But it's better to resolve the issue you're having in order to use latest plugin version.

**Comment by certilremy** [comment]
I used the previous version, every thing work perfect now. thank you for this awesome plugin
