### ISSUE TITLE
Is there any way to disable downloads being included in search results?

### ISSUE THREAD

**Issue by TheRobotFactory** [Arsenal21/simple-download-monitor#47]
I'm using the plugin purely to give a download button with a log of how many times a file has been downloaded, I don't use any of the other fields in the download item page. 

how do I stop the download items appearing in search results?

**Comment by Arsenal21** [comment]
You can create an empty .htaccess file (in the folder where you keep your downloads) with the following content. That will prevent search engines from indexing that particular folder
`
Options -Indexes
`
