### ISSUE TITLE
Downloads by country map is not responsive

### ISSUE THREAD

**Issue by mbrsolution** [Arsenal21/simple-download-monitor#48]
Hi, just wanted to report that the Downloads by country map is not responsive. Is this something that can be fixed?

You can see in the following image, part of the world is missing when the browser is reduced in size.

![downloads-by-country-not-responsive](https://user-images.githubusercontent.com/38054628/60403473-21e34480-9be1-11e9-8653-46d1a9ee9e9e.png)

Thank you

**Comment by erommel** [comment]
I've applied a little fix for this https://github.com/Arsenal21/simple-download-monitor/commit/11d36622a9979312883df9005884717229ecd775

It's still not responsive if you resize browser, but looks much better on mobile devices (by trying to fit the screen rather than having a fixed position).

**Comment by mbrsolution** [comment]
Thank you Alexander, 

When is the next release coming out so that I can test this fix?

**Comment by erommel** [comment]
Current version should have this fix implemented.

**Comment by mbrsolution** [comment]
This is what I see with the current version 3.8.3.

**Comment by Arsenal21** [comment]
This is a low priority one for now.

**Comment by erommel** [comment]
@mbrsolution , it's difficult to make this one dynamically responsive (e.g. when you resize the browser with page loaded). The map tries to get appropriate size on page load. You can test that yourself by either accessing it from your mobile device or by resizing your browser and then reloading the page.
