### ISSUE TITLE
Add shortcode argument to make specific download not protected

### ISSUE THREAD

**Issue by johnzenaida** [Arsenal21/simple-download-monitor#52]
I have the download links protected where the user needs to login before download. Is there anyway to add an argument as such do_not_download_protect="1" or something similar. Thanks again.

**Comment by erommel** [comment]
Hi. I've added per-item `Ignore "Only Allow Logged-in Users to Download" global setting for this item` option. If enabled, the item can be downloaded even if `Only Allow Logged-in Users to Download` option is enabled.

**Comment by erommel** [comment]
To test this functionality, you should install this plugin version on your site:
[simple-download-monitor.zip](https://github.com/Arsenal21/simple-download-monitor/files/4469849/simple-download-monitor.zip)

**Comment by Arsenal21** [comment]
Works nicely.
