### ISSUE TITLE
Maybe update a link.

### ISSUE THREAD

**Issue by mbrsolution** [Arsenal21/simple-download-monitor#55]
Hi, the following image displays the following link **here**.

![wordpress-simple-download-monitor-plugin-shortcodes](https://user-images.githubusercontent.com/38054628/79286644-9aaf5500-7f04-11ea-925a-dda19f7eadca.png)

The above link is pointing to the following URL.

https://www.tipsandtricks-hq.com/simple-wordpress-download-monitor-plugin

However you might want to point the link to the new site.

https://simple-download-monitor.com/miscellaneous-shortcodes-and-shortcode-parameters/

What do you think?

**Comment by Arsenal21** [comment]
Good idea. I have updated the documentation URL
