### ISSUE TITLE
I might have found a bug

### ISSUE THREAD

**Issue by mbrsolution** [Arsenal21/simple-download-monitor#57]
Hi, I was testing the open a pdf file in a new window option. I decided to test this because of the following support thread https://wordpress.org/support/topic/i-have-open-download-in-a-new-window-selected-not-working/, which is now resolved :)

I inserted the download shortcode using the **SDM Downloads Button**. I selected the option to open up the download in a new window. The following is the shortcode it created. I notice the following parameter **new_window="1"** added in the shortcode which makes sense.

`[sdm_download id="20" fancy="0" new_window="1" color="green"]`

Now my question is this. What is the purpose of enabling  the following feature **Open download in a new window.** located under **Miscellaneous Download Item Properties.** which does not work unless you also enable selecting to open up the download in a new window using the **SDM Downloads Button**? 

And I tested my theory above by carrying out the following tests. 

**Test 1**

I did not enable  **Open download in a new window.** located under **Miscellaneous Download Item Properties.**. I only enabled selecting to open up the download in a new window using the **SDM Downloads Button** and it worked. The pdf file opened up in a new.

**Test 2**

I enabled  **Open download in a new window.** located under **Miscellaneous Download Item Properties.**. I did not enable selecting to open up the download in a new window using the **SDM Downloads Button** and it did not work. The pdf file did not open up in a new.

Let me know if you need more information.

Thank you

**Comment by Arsenal21** [comment]
I just tested it and it works fine. 

Only need to check/enable the "Open download in a new window" option in the download configuration. Nothing needs to be done in the shortcode (that shortcode parameter was old functionality).

It maybe that the PHP Dispatch maybe enabled in that download you are testing with. Make sure PHP Dispatch is disabled. PHP Dispatch can't open a new download since the new tab will be forced closed by the browser and it will stream the download to the current window (this is a new behavior from the browser).

**Comment by mbrsolution** [comment]
Hi, unfortunately it does not work for me unless I add the parameter in the shortcode.  I don't have anything enable in the download file except **Open download in a new window**.

The same happened to the user who created the support ticket above. They also had to add the parameter in the shortcode to get it to work in their site. So there is something that is not working correctly in my humble opinion.

Kind regards
