### ISSUE TITLE
Feature Request: Adding extra optional buttons

### ISSUE THREAD

**Issue by rafisics** [Arsenal21/simple-download-monitor#67]
Hi, I am currently using this plugin to allow my website viewers to download free PDF ebooks. I like to provide an extra button to read the book online alongside the download option. My desired structure for the `fancy 2` template is like the following: 

![download_monitor](https://user-images.githubusercontent.com/68302816/129435593-44bf8ef8-bcae-4e23-858c-1eab502888b9.png)

In the `Read Online` button, I wish to add a hyperlink to a different page so that the viewers may preview or read some portion of the book without downloading. Also, I like to show the `download counter` option inside the `fancy 2` template.

**Comment by Arsenal21** [comment]
I think we can add an option in the shortcode to have a "Read More" URL. That will then get added in the fancy display with a "Read More" URL.

**Comment by rafisics** [comment]
> I think we can add an option in the shortcode to have a "Read More" URL. That will then get added in the fancy display with a "Read More" URL.

Looking forward to getting such an option.

**Comment by rafisics** [comment]
> I think we can add an option in the shortcode to have a "Read More" URL. That will then get added in the fancy display with a "Read More" URL.

Any chance to provide this feature in the next update?

**Comment by Arsenal21** [comment]
I will try to. I can't promise it unfortunately. 

We are currently working on some features for our following plugin which is keeping me busy:
https://wordpress.org/plugins/wp-express-checkout/

**Comment by Arsenal21** [comment]
We are working on a shortcode parameter for this. We will have more details when we prepare the next release of the plugin within the next week or so.
